package com.client.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAT_MSG".
 */
public class ChatMsg {

    private Long id;
    /** Not-null value. */
    private String FromUser;
    /** Not-null value. */
    private String ToUser;
    /** Not-null value. */
    private java.util.Date MsgDate;
    /** Not-null value. */
    private String MsgType;
    private byte MsgBody;

    public ChatMsg() {
    }

    public ChatMsg(Long id) {
        this.id = id;
    }

    public ChatMsg(Long id, String FromUser, String ToUser, java.util.Date MsgDate, String MsgType, byte MsgBody) {
        this.id = id;
        this.FromUser = FromUser;
        this.ToUser = ToUser;
        this.MsgDate = MsgDate;
        this.MsgType = MsgType;
        this.MsgBody = MsgBody;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFromUser() {
        return FromUser;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFromUser(String FromUser) {
        this.FromUser = FromUser;
    }

    /** Not-null value. */
    public String getToUser() {
        return ToUser;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToUser(String ToUser) {
        this.ToUser = ToUser;
    }

    /** Not-null value. */
    public java.util.Date getMsgDate() {
        return MsgDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMsgDate(java.util.Date MsgDate) {
        this.MsgDate = MsgDate;
    }

    /** Not-null value. */
    public String getMsgType() {
        return MsgType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMsgType(String MsgType) {
        this.MsgType = MsgType;
    }

    public byte getMsgBody() {
        return MsgBody;
    }

    public void setMsgBody(byte MsgBody) {
        this.MsgBody = MsgBody;
    }

}
