package com.client.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAT_MSG".
 */
public class ChatMsg {

    /** Not-null value. */
    private String Fromuser;
    /** Not-null value. */
    private String Touser;
    /** Not-null value. */
    private java.util.Date Msgdate;
    private int Msgtype;
    /** Not-null value. */
    private byte[] Msgbody;

    public ChatMsg() {
    }

    public ChatMsg(String Fromuser, String Touser, java.util.Date Msgdate, int Msgtype, byte[] Msgbody) {
        this.Fromuser = Fromuser;
        this.Touser = Touser;
        this.Msgdate = Msgdate;
        this.Msgtype = Msgtype;
        this.Msgbody = Msgbody;
    }

    /** Not-null value. */
    public String getFromuser() {
        return Fromuser;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFromuser(String Fromuser) {
        this.Fromuser = Fromuser;
    }

    /** Not-null value. */
    public String getTouser() {
        return Touser;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTouser(String Touser) {
        this.Touser = Touser;
    }

    /** Not-null value. */
    public java.util.Date getMsgdate() {
        return Msgdate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMsgdate(java.util.Date Msgdate) {
        this.Msgdate = Msgdate;
    }

    public int getMsgtype() {
        return Msgtype;
    }

    public void setMsgtype(int Msgtype) {
        this.Msgtype = Msgtype;
    }

    /** Not-null value. */
    public byte[] getMsgbody() {
        return Msgbody;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMsgbody(byte[] Msgbody) {
        this.Msgbody = Msgbody;
    }

}
