package com.client.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.client.models.User;
import com.client.models.ChatMsg;
import com.client.models.Friends;

import com.client.models.UserDao;
import com.client.models.ChatMsgDao;
import com.client.models.FriendsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig chatMsgDaoConfig;
    private final DaoConfig friendsDaoConfig;

    private final UserDao userDao;
    private final ChatMsgDao chatMsgDao;
    private final FriendsDao friendsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        chatMsgDaoConfig = daoConfigMap.get(ChatMsgDao.class).clone();
        chatMsgDaoConfig.initIdentityScope(type);

        friendsDaoConfig = daoConfigMap.get(FriendsDao.class).clone();
        friendsDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        chatMsgDao = new ChatMsgDao(chatMsgDaoConfig, this);
        friendsDao = new FriendsDao(friendsDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(ChatMsg.class, chatMsgDao);
        registerDao(Friends.class, friendsDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        chatMsgDaoConfig.getIdentityScope().clear();
        friendsDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ChatMsgDao getChatMsgDao() {
        return chatMsgDao;
    }

    public FriendsDao getFriendsDao() {
        return friendsDao;
    }

}
