package com.client.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.client.models.User;
import com.client.models.Token;

import com.client.models.UserDao;
import com.client.models.TokenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig tokenDaoConfig;

    private final UserDao userDao;
    private final TokenDao tokenDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        tokenDaoConfig = daoConfigMap.get(TokenDao.class).clone();
        tokenDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        tokenDao = new TokenDao(tokenDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Token.class, tokenDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        tokenDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TokenDao getTokenDao() {
        return tokenDao;
    }

}
