package com.client.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.client.models.ChatMsg;
import com.client.models.User;

import com.client.models.ChatMsgDao;
import com.client.models.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatMsgDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ChatMsgDao chatMsgDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatMsgDaoConfig = daoConfigMap.get(ChatMsgDao.class).clone();
        chatMsgDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        chatMsgDao = new ChatMsgDao(chatMsgDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(ChatMsg.class, chatMsgDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        chatMsgDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public ChatMsgDao getChatMsgDao() {
        return chatMsgDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
