package com.client.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FRIENDS".
 */
public class Friends {

    private Long id;
    /** Not-null value. */
    private String Username;
    /** Not-null value. */
    private byte[] Pic;

    public Friends() {
    }

    public Friends(Long id) {
        this.id = id;
    }

    public Friends(Long id, String Username, byte[] Pic) {
        this.id = id;
        this.Username = Username;
        this.Pic = Pic;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUsername() {
        return Username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String Username) {
        this.Username = Username;
    }

    /** Not-null value. */
    public byte[] getPic() {
        return Pic;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPic(byte[] Pic) {
        this.Pic = Pic;
    }

}
