package com.client.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String Username;
    /** Not-null value. */
    private String Password;
    private boolean Islogin;
    /** Not-null value. */
    private java.util.Date Lastlogin;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String Username, String Password, boolean Islogin, java.util.Date Lastlogin) {
        this.id = id;
        this.Username = Username;
        this.Password = Password;
        this.Islogin = Islogin;
        this.Lastlogin = Lastlogin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUsername() {
        return Username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String Username) {
        this.Username = Username;
    }

    /** Not-null value. */
    public String getPassword() {
        return Password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String Password) {
        this.Password = Password;
    }

    public boolean getIslogin() {
        return Islogin;
    }

    public void setIslogin(boolean Islogin) {
        this.Islogin = Islogin;
    }

    /** Not-null value. */
    public java.util.Date getLastlogin() {
        return Lastlogin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLastlogin(java.util.Date Lastlogin) {
        this.Lastlogin = Lastlogin;
    }

}
