package com.client.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String UserName;
    /** Not-null value. */
    private String PassWord;
    private boolean IsLogin;
    /** Not-null value. */
    private java.util.Date LastLogin;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String UserName, String PassWord, boolean IsLogin, java.util.Date LastLogin) {
        this.id = id;
        this.UserName = UserName;
        this.PassWord = PassWord;
        this.IsLogin = IsLogin;
        this.LastLogin = LastLogin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserName() {
        return UserName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    /** Not-null value. */
    public String getPassWord() {
        return PassWord;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassWord(String PassWord) {
        this.PassWord = PassWord;
    }

    public boolean getIsLogin() {
        return IsLogin;
    }

    public void setIsLogin(boolean IsLogin) {
        this.IsLogin = IsLogin;
    }

    /** Not-null value. */
    public java.util.Date getLastLogin() {
        return LastLogin;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLastLogin(java.util.Date LastLogin) {
        this.LastLogin = LastLogin;
    }

}
